// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FilterModalController from "./filter_modal_controller"
application.register("filter-modal", FilterModalController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import StoreSuggestionsController from "./store_suggestions_controller"
application.register("store-suggestions", StoreSuggestionsController)
